# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: feer
services:
  app:
    image: feer
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - SPRING_CASSANDRA_CONTACTPOINTS=cassandra
      - JHIPSTER_SLEEP=10
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-migration:
        condition: service_completed_successfully
      keycloak:
        condition: service_healthy
  cassandra:
    extends:
      file: ./cassandra.yml
      service: cassandra
  cassandra-migration:
    extends:
      file: ./cassandra.yml
      service: cassandra-migration
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
