# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: feer
services:
  cassandra:
    extends:
      file: ./cassandra.yml
      service: cassandra
  cassandra-migration:
    extends:
      file: ./cassandra.yml
      service: cassandra-migration
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
